### ISSUE TITLE
Discuss and Resolve Exercises for The Upcoming Semesters

### ISSUE THREAD

**Issue by melsigl** [FAU-CS6/KDD#61]
PR #59 showed that several unresolved questions exist. As we aim to continuously improve our lectures as well as the exercises, we should discuss them in order to implement them before the upcoming semester.

As of now, the discussed points so far include, but may not be limited to:
1. Split exercise notebooks per week or per algorithm? What is the best strategy here? What confuses the students less? What strategy provides the most intuitive take on for students?
2. Follow an object-oriented paradigm that is consistent with `sklearn` and consolidates all necessary state variables and functions to provide an intuitive fit/predict procedure that does not jeopardize a guided step-by-step walk through the algorithm. Again, the questions are: What is the best strategy here? 

Each party concerned already commented on their respective opinion on these matters including advantages, disadvantages, as well as their individual opinions for the aforementioned points. See PR #59 for a detailed discussion.

Further comments and topics that we should discuss in the future shall be added here, or mentioned directly in our weekly Jour Fixe.

**Comment by dominik-probst** [comment]
Due to the comprehensive revision of exercises in the summer semester 2024 (see also #77), this issue is outdated.
